# Generated by Django 5.1.1 on 2024-09-07 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome padrão', max_length=255)),
                ('descricao', models.TextField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_produto', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produto')),
                ('marca', models.CharField(max_length=50)),
                ('compatibilidade', models.CharField(default='Não aplicável', max_length=100)),
            ],
            bases=('produtos.produto',),
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produto')),
                ('plataforma', models.CharField(choices=[('PC', 'PC'), ('Xbox', 'Xbox'), ('PlayStation5', 'PlayStation5'), ('Nintendo', 'Nintendo')], max_length=20)),
                ('genero', models.CharField(choices=[('Ação', 'Ação'), ('Aventura', 'Aventura'), ('RPG', 'RPG'), ('Desporto', 'Desporto'), ('Corrida', 'Corrida')], max_length=20)),
                ('data_lancamento', models.DateField()),
                ('desenvolvedora', models.CharField(max_length=100)),
            ],
            bases=('produtos.produto',),
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
